export const houseInputs = [
  {
    id: "name",
    label: "Name",
    type: "text",
    placeholder: "5 cent 1500sqft house",
    errorMessage: "enter name",
  },
  {
    id: "type",
    label: "Type",
    type: "text",
    placeholder: "house or land",
    errorMessage: "This Field is Required",
  },
  {
    id: "city",
    label: "City",
    type: "text",
    placeholder: "Type city",
    errorMessage: "This Field is Required",
  },
  {
    id: "address",
    label: "Address",
    type: "text",
    placeholder: "Address",
    errorMessage: "This Field is Required",
  },
  {
    id: "distance",
    label: "Distance",
    type: "text",
    placeholder: "Distance",
    errorMessage: "This Field is Required",
  },
  {
    id: "title",
    label: "Title",
    type: "text",
    placeholder: "title",
    errorMessage: "This Field is Required",
  },
  {
    id: "desc",
    label: "Description",
    type: "text",
    placeholder: "1550sqft 2 floor house for sale",
    errorMessage: "This Field is Required",
  },
  {
    id: "listedBy",
    label: "Listed By",
    type: "text",
    placeholder: "builder Owner or Dealer",
    errorMessage: "This Field is Required",
  },
  {
    id: "price",
    label: "Price",
    type: "text",
    placeholder: "Price",
    errorMessage: "This Field is Required",
  },
  {
    id: "bedRoom",
    label: "Bed Rooms",
    type: "Number",
    placeholder: "Bed Rooms",
    errorMessage: "This Field is Required",
  },
  {
    id: "bathRoom",
    label: "Bath Rooms",
    type: "Number",
    placeholder: "Bath Rooms",
    errorMessage: "This Field is Required",
  },
  {
    id: "balcony",
    label: "Balcony",
    type: "Number",
    placeholder: "Balcony",
    errorMessage: "This Field is Required",
  },
  {
    id: "floors",
    label: "Floors",
    type: "Number",
    placeholder: "Floors",
    errorMessage: "This Field is Required",
  },
  {
    id: "plotArea",
    label: "plotArea",
    type: "text",
    placeholder: "5 cent",
    errorMessage: "This Field is Required",
  },
];

export const landInputs = [
  {
    id: "name",
    label: "Name",
    type: "text",
    placeholder: "5 cent 1500sqft house",
    errorMessage: "Enter name",
  },
  {
    id: "type",
    label: "Type",
    type: "text",
    placeholder: "house or land",
    errorMessage: "This Field is Required",
  },
  {
    id: "city",
    label: "City",
    type: "text",
    placeholder: "Type city",
    errorMessage: "enter city",
  },
  {
    id: "address",
    label: "Address",
    type: "text",
    placeholder: "Address",
    errorMessage: "This Field is Required",
  },
  {
    id: "distance",
    label: "Distance",
    type: "text",
    placeholder: "Distance",
    errorMessage: "This Field is Required",
  },
  {
    id: "title",
    label: "Title",
    type: "text",
    placeholder: "title",
    errorMessage: "This Field is Required",
  },
  {
    id: "desc",
    label: "Description",
    type: "text",
    placeholder: "1550sqft 2 floor house for sale",
    errorMessage: "This Field is Required",
  },
  {
    id: "listedBy",
    label: "Listed By",
    type: "text",
    placeholder: "builder Owner or Dealer",
    errorMessage: "This Field is Required",
  },
  {
    id: "price",
    label: "Price",
    type: "text",
    placeholder: "Price",
    errorMessage: "This Field is Required",
  },
  {
    id: "plotArea",
    label: "plotArea",
    type: "text",
    placeholder: "5 cent",
    errorMessage: "This Field is Required",
  },
  // {
  //   id: "facing",
  //   label: "Facing",
  //   type: "text",
  //   placeholder: "East West North South",
  // },
  // {
  //   id: "isCurrentAndWater",
  //   label: "isCurrentAndWater",
  //   type: "checkbox",
  // },
  // {
  //   id: "featured",
  //   label: "featured ?",
  //   type: "checkbox",
  // },
];

export const ticketInputs = [
  {
    id: "subject",
    label: "Subject",
    type: "text",
    placeholder: "ssl issue",
    errorMessage: "This Field is Required",
  },
  {
    id: "openAt",
    label: "Issue Found On",
    type: "Date",
    placeholder: new Date(),
    errorMessage: "This Field is Required",
  },
];
